# Generated by Django 5.1.3 on 2025-04-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('web_designer', 'Website Designer'), ('brand_developer', 'Brand Developer'), ('content_marketer', 'Content Marketer'), ('paid_media_specialist', 'Paid Media Specialist'), ('customer', 'Customer')], max_length=30, null=True),
        ),
    ]
