# Generated by Django 5.2.4 on 2025-08-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linetrendy', '0002_category_slug_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='linetrendy.product'),
        ),
    ]
