# Generated by Django 5.2.4 on 2025-08-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linetrendy', '0004_category_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
