# Generated by Django 5.2.4 on 2025-08-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linetrendy', '0005_alter_billingaddress_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
