# Generated by Django 5.2.4 on 2025-10-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linetrendy', '0020_testimonials_alter_newsletter_subscribed_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
